services:
  exercice_3:
    image: postgres
    env_file: .env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - POSTGRES_PASSWORD

volumes:
  postgres_data:

secrets:
  POSTGRES_PASSWORD:
    file: ./db_password.txt
